import "./root.css"
import "./style.css"

import "./banner"
import "./hit"
import "./icons"
import "./infomusic"
import "./logo"
import "./members"
import "./membersdesktop"
import "./membersmobile"
import "./pause"
import "./play"
import "./player"
import "./progress"
import "./musicduration"
import "./pictures"
